import pg from 'pg';
import { AsyncLocalStorage } from 'node:async_hooks';

// BIGINT / NUMERIC come back as strings by default; amounts are integer cents well within 2^53.
pg.types.setTypeParser(20, (v) => Number(v));
pg.types.setTypeParser(1700, (v) => Number(v));

export const NOW_TEXT = `to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')`;

export interface RunResult {
  changes: number;
  lastInsertRowid: number | undefined;
}

const sqlCache = new Map<string, string>();
/** Converts `?` placeholders to `$1..$n`, ignoring anything inside quoted literals/identifiers. */
export function toPgSql(sql: string): string {
  const hit = sqlCache.get(sql);
  if (hit) return hit;
  let out = '';
  let n = 0;
  let quote: string | null = null;
  for (const ch of sql) {
    if (quote) {
      if (ch === quote) quote = null;
      out += ch;
    } else if (ch === "'" || ch === '"') {
      quote = ch;
      out += ch;
    } else if (ch === '?') {
      out += `$${++n}`;
    } else out += ch;
  }
  if (sqlCache.size < 2000) sqlCache.set(sql, out);
  return out;
}

export class Statement {
  constructor(
    private readonly db: DB,
    private readonly sql: string,
  ) {}
  async get(...params: unknown[]): Promise<any> {
    return (await this.db.query(this.sql, params)).rows[0];
  }
  async all(...params: unknown[]): Promise<any[]> {
    return (await this.db.query(this.sql, params)).rows;
  }
  async run(...params: unknown[]): Promise<RunResult> {
    let sql = this.sql;
    if (/^\s*insert\b/i.test(sql) && !/\breturning\b/i.test(sql)) sql += ' RETURNING *';
    const r = await this.db.query(sql, params);
    const id = r.rows[0]?.id;
    return { changes: r.rowCount ?? 0, lastInsertRowid: id === undefined ? undefined : Number(id) };
  }
}

export interface DbOptions {
  url: string;
  /** false = plain connection; 'require' = TLS without CA verification; object = full pg TLS options. */
  ssl?: false | 'require' | pg.PoolConfig['ssl'];
  /** Use a dedicated schema (tests / isolation). Must be a simple identifier. */
  schema?: string;
  max?: number;
  statementTimeoutMs?: number;
}

export class DB {
  readonly pool: pg.Pool;
  private readonly tx = new AsyncLocalStorage<{ client: pg.PoolClient; depth: number }>();

  constructor(opts: DbOptions) {
    if (opts.schema && !/^[a-z_][a-z0-9_]{0,62}$/.test(opts.schema)) throw new Error('Invalid schema name.');
    const url = new URL(opts.url);
    // TLS is configured explicitly below; drop URL ssl params so they cannot silently override it.
    for (const k of ['sslmode', 'sslcert', 'sslkey', 'sslrootcert', 'ssl']) url.searchParams.delete(k);
    this.pool = new pg.Pool({
      connectionString: url.toString(),
      ssl: opts.ssl === 'require' ? { rejectUnauthorized: false } : opts.ssl || undefined,
      max: opts.max ?? 5,
      idleTimeoutMillis: 30_000,
      connectionTimeoutMillis: 15_000,
      statement_timeout: opts.statementTimeoutMs ?? 30_000,
      application_name: 'personal-finance-hq',
      options: opts.schema ? `-c search_path=${opts.schema}` : undefined,
    });
    this.pool.on('error', (e) => console.error('Database pool error:', e.message));
  }

  prepare(sql: string) {
    return new Statement(this, toPgSql(sql));
  }

  query(sql: string, params: unknown[] = []) {
    const t = this.tx.getStore();
    return (t ? t.client : this.pool).query(sql, params as unknown[]);
  }

  /** Runs multi-statement SQL without parameters. */
  async exec(sql: string) {
    await this.query(sql);
  }

  /** db.transaction(fn)() — returns a function that runs fn atomically. Nested calls use savepoints. */
  transaction<A extends unknown[], R>(fn: (...args: A) => Promise<R>) {
    return async (...args: A): Promise<R> => {
      const cur = this.tx.getStore();
      if (cur) {
        const sp = `sp_${cur.depth + 1}`;
        await cur.client.query(`SAVEPOINT ${sp}`);
        try {
          const r = await this.tx.run({ client: cur.client, depth: cur.depth + 1 }, () => fn(...args));
          await cur.client.query(`RELEASE SAVEPOINT ${sp}`);
          return r;
        } catch (e) {
          await cur.client.query(`ROLLBACK TO SAVEPOINT ${sp}`);
          throw e;
        }
      }
      const client = await this.pool.connect();
      try {
        await client.query('BEGIN');
        const r = await this.tx.run({ client, depth: 0 }, () => fn(...args));
        await client.query('COMMIT');
        return r;
      } catch (e) {
        await client.query('ROLLBACK').catch(() => undefined);
        throw e;
      } finally {
        client.release();
      }
    };
  }

  async close() {
    await this.pool.end();
  }
}

const ID = 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY';
const TS = `TEXT NOT NULL DEFAULT ${NOW_TEXT}`;

const SCHEMA = `
CREATE TABLE IF NOT EXISTS users (
  id ${ID},
  name TEXT NOT NULL,
  base_currency TEXT NOT NULL DEFAULT 'CAD',
  created_at ${TS}
);

CREATE TABLE IF NOT EXISTS accounts (
  id ${ID},
  user_id BIGINT NOT NULL DEFAULT 1 REFERENCES users(id),
  code TEXT NOT NULL,
  name TEXT NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('asset','liability','equity','income','expense')),
  subtype TEXT NOT NULL,
  currency TEXT NOT NULL DEFAULT 'CAD',
  parent_id BIGINT REFERENCES accounts(id),
  institution TEXT,
  aliases TEXT,
  description TEXT,
  sort_order BIGINT NOT NULL DEFAULT 0,
  is_active BIGINT NOT NULL DEFAULT 1,
  is_system BIGINT NOT NULL DEFAULT 0,
  interest_rate DOUBLE PRECISION,
  min_payment BIGINT,
  created_at ${TS},
  updated_at ${TS},
  UNIQUE (user_id, code)
);

CREATE TABLE IF NOT EXISTS securities (
  id ${ID},
  user_id BIGINT NOT NULL DEFAULT 1,
  symbol TEXT NOT NULL,
  name TEXT,
  currency TEXT NOT NULL DEFAULT 'CAD',
  last_price BIGINT,
  price_date TEXT,
  UNIQUE (user_id, symbol)
);

CREATE TABLE IF NOT EXISTS journal_entries (
  id ${ID},
  user_id BIGINT NOT NULL DEFAULT 1,
  date TEXT NOT NULL,
  description TEXT NOT NULL,
  payee TEXT,
  memo TEXT,
  transaction_type TEXT NOT NULL DEFAULT 'manual',
  source TEXT NOT NULL DEFAULT 'manual',
  currency TEXT NOT NULL DEFAULT 'CAD',
  fx_rate DOUBLE PRECISION NOT NULL DEFAULT 1,
  raw_input TEXT,
  explanation TEXT,
  metadata TEXT,
  import_hash TEXT,
  reversal_of BIGINT REFERENCES journal_entries(id),
  reversed_by BIGINT REFERENCES journal_entries(id),
  recurring_id BIGINT,
  created_at ${TS}
);
CREATE INDEX IF NOT EXISTS idx_entries_date ON journal_entries(user_id, date);
CREATE INDEX IF NOT EXISTS idx_entries_hash ON journal_entries(import_hash);

CREATE TABLE IF NOT EXISTS journal_lines (
  id ${ID},
  entry_id BIGINT NOT NULL REFERENCES journal_entries(id),
  account_id BIGINT NOT NULL REFERENCES accounts(id),
  debit BIGINT NOT NULL DEFAULT 0,
  credit BIGINT NOT NULL DEFAULT 0,
  original_debit BIGINT NOT NULL DEFAULT 0,
  original_credit BIGINT NOT NULL DEFAULT 0,
  memo TEXT,
  security_id BIGINT REFERENCES securities(id),
  quantity DOUBLE PRECISION,
  reconciliation_id BIGINT,
  cleared BIGINT NOT NULL DEFAULT 0,
  CHECK (debit >= 0 AND credit >= 0),
  CHECK (NOT (debit > 0 AND credit > 0))
);
CREATE INDEX IF NOT EXISTS idx_lines_account ON journal_lines(account_id);
CREATE INDEX IF NOT EXISTS idx_lines_entry ON journal_lines(entry_id);

CREATE TABLE IF NOT EXISTS audit_log (
  id ${ID},
  user_id BIGINT NOT NULL DEFAULT 1,
  ts ${TS},
  action TEXT NOT NULL,
  entity TEXT NOT NULL,
  entity_id BIGINT,
  details TEXT
);

CREATE TABLE IF NOT EXISTS budgets (
  id ${ID},
  user_id BIGINT NOT NULL DEFAULT 1,
  account_id BIGINT NOT NULL REFERENCES accounts(id),
  month TEXT NOT NULL,
  amount BIGINT NOT NULL,
  UNIQUE (user_id, account_id, month)
);

CREATE TABLE IF NOT EXISTS reconciliations (
  id ${ID},
  user_id BIGINT NOT NULL DEFAULT 1,
  account_id BIGINT NOT NULL REFERENCES accounts(id),
  statement_date TEXT NOT NULL,
  statement_balance BIGINT NOT NULL,
  status TEXT NOT NULL DEFAULT 'in_progress',
  created_at ${TS},
  completed_at TEXT
);

CREATE TABLE IF NOT EXISTS recurring_transactions (
  id ${ID},
  user_id BIGINT NOT NULL DEFAULT 1,
  description TEXT NOT NULL,
  frequency TEXT NOT NULL,
  next_date TEXT NOT NULL,
  end_date TEXT,
  template TEXT NOT NULL,
  auto_post BIGINT NOT NULL DEFAULT 1,
  is_active BIGINT NOT NULL DEFAULT 1,
  created_at ${TS}
);

CREATE TABLE IF NOT EXISTS merchant_rules (
  id ${ID},
  user_id BIGINT NOT NULL DEFAULT 1,
  pattern TEXT NOT NULL,
  account_id BIGINT NOT NULL REFERENCES accounts(id),
  hits BIGINT NOT NULL DEFAULT 1,
  UNIQUE (user_id, pattern)
);

CREATE TABLE IF NOT EXISTS fx_rates (
  currency TEXT NOT NULL,
  date TEXT NOT NULL,
  rate DOUBLE PRECISION NOT NULL,
  PRIMARY KEY (currency, date)
);

CREATE TABLE IF NOT EXISTS sessions (
  id TEXT PRIMARY KEY,
  csrf TEXT NOT NULL,
  cred_fp TEXT NOT NULL,
  created_at BIGINT NOT NULL,
  last_seen BIGINT NOT NULL,
  expires_at BIGINT NOT NULL,
  ip TEXT,
  user_agent TEXT
);

CREATE TABLE IF NOT EXISTS goals (
  id ${ID},
  user_id BIGINT NOT NULL DEFAULT 1,
  name TEXT NOT NULL,
  kind TEXT NOT NULL DEFAULT 'savings',
  target_amount BIGINT NOT NULL,
  target_date TEXT,
  account_ids TEXT,
  manual_amount BIGINT NOT NULL DEFAULT 0,
  notes TEXT,
  is_archived BIGINT NOT NULL DEFAULT 0,
  created_at ${TS}
);

CREATE TABLE IF NOT EXISTS settings (
  user_id BIGINT NOT NULL DEFAULT 1,
  key TEXT NOT NULL,
  value TEXT,
  PRIMARY KEY (user_id, key)
);
`;

export const TABLES = [
  'users', 'accounts', 'securities', 'journal_entries', 'journal_lines', 'audit_log', 'budgets', 'reconciliations',
  'recurring_transactions', 'merchant_rules', 'fx_rates', 'sessions', 'goals', 'settings',
] as const;

const PROTECT = `
CREATE OR REPLACE FUNCTION pfhq_block_change() RETURNS trigger LANGUAGE plpgsql AS $fn$
BEGIN
  RAISE EXCEPTION '%', TG_ARGV[0] USING ERRCODE = 'P0001';
END
$fn$;

DROP TRIGGER IF EXISTS trg_lines_no_delete ON journal_lines;
CREATE TRIGGER trg_lines_no_delete BEFORE DELETE ON journal_lines
  FOR EACH ROW EXECUTE FUNCTION pfhq_block_change('Posted journal lines cannot be deleted');
DROP TRIGGER IF EXISTS trg_entries_no_delete ON journal_entries;
CREATE TRIGGER trg_entries_no_delete BEFORE DELETE ON journal_entries
  FOR EACH ROW EXECUTE FUNCTION pfhq_block_change('Posted journal entries cannot be deleted; reverse them instead');
DROP TRIGGER IF EXISTS trg_lines_amounts_immutable ON journal_lines;
CREATE TRIGGER trg_lines_amounts_immutable BEFORE UPDATE ON journal_lines
  FOR EACH ROW WHEN (
    OLD.entry_id IS DISTINCT FROM NEW.entry_id OR OLD.account_id IS DISTINCT FROM NEW.account_id
    OR OLD.debit IS DISTINCT FROM NEW.debit OR OLD.credit IS DISTINCT FROM NEW.credit
    OR OLD.original_debit IS DISTINCT FROM NEW.original_debit OR OLD.original_credit IS DISTINCT FROM NEW.original_credit
    OR OLD.security_id IS DISTINCT FROM NEW.security_id OR OLD.quantity IS DISTINCT FROM NEW.quantity)
  EXECUTE FUNCTION pfhq_block_change('Posted journal amounts are immutable');
DROP TRIGGER IF EXISTS trg_audit_no_update ON audit_log;
CREATE TRIGGER trg_audit_no_update BEFORE UPDATE OR DELETE ON audit_log
  FOR EACH ROW EXECUTE FUNCTION pfhq_block_change('Audit log is append-only');
DROP TRIGGER IF EXISTS trg_ledger_no_truncate ON journal_lines;
CREATE TRIGGER trg_ledger_no_truncate BEFORE TRUNCATE ON journal_lines
  FOR EACH STATEMENT EXECUTE FUNCTION pfhq_block_change('The ledger cannot be truncated');
DROP TRIGGER IF EXISTS trg_entries_no_truncate ON journal_entries;
CREATE TRIGGER trg_entries_no_truncate BEFORE TRUNCATE ON journal_entries
  FOR EACH STATEMENT EXECUTE FUNCTION pfhq_block_change('The ledger cannot be truncated');
DROP TRIGGER IF EXISTS trg_audit_no_truncate ON audit_log;
CREATE TRIGGER trg_audit_no_truncate BEFORE TRUNCATE ON audit_log
  FOR EACH STATEMENT EXECUTE FUNCTION pfhq_block_change('Audit log is append-only');
`;

// Supabase exposes the public schema through its REST API to the anon/authenticated roles.
// Row-level security with no policies plus explicit revokes keeps the ledger reachable only via this server.
const LOCKDOWN = `
${TABLES.map((t) => `ALTER TABLE ${t} ENABLE ROW LEVEL SECURITY;`).join('\n')}
DO $do$
DECLARE r TEXT;
BEGIN
  FOREACH r IN ARRAY ARRAY['anon', 'authenticated'] LOOP
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = r) THEN
      EXECUTE format('REVOKE ALL ON ALL TABLES IN SCHEMA %I FROM %I', current_schema(), r);
      EXECUTE format('REVOKE ALL ON ALL SEQUENCES IN SCHEMA %I FROM %I', current_schema(), r);
      EXECUTE format('REVOKE ALL ON FUNCTION pfhq_block_change() FROM %I', r);
    END IF;
  END LOOP;
END
$do$;
`;

export async function openDb(opts: DbOptions): Promise<DB> {
  if (opts.schema) {
    const admin = new pg.Client({ connectionString: opts.url, ssl: opts.ssl === 'require' ? { rejectUnauthorized: false } : opts.ssl || undefined });
    await admin.connect();
    try {
      await admin.query(`CREATE SCHEMA IF NOT EXISTS ${opts.schema}`);
    } finally {
      await admin.end();
    }
  }
  const db = new DB(opts);
  await migrate(db);
  return db;
}

async function migrate(db: DB) {
  await db.transaction(async () => {
    // Serialises concurrent migrations (e.g. two instances starting at once).
    await db.query('SELECT pg_advisory_xact_lock(727274)');
    await db.exec(SCHEMA);
    await db.exec(PROTECT);
    await db.exec(LOCKDOWN);
  })();
}

/** Re-aligns identity sequences after rows were inserted with explicit ids (restore/import). */
export async function resetSequences(db: DB) {
  for (const t of TABLES) {
    if (t === 'fx_rates' || t === 'sessions' || t === 'settings') continue;
    await db.query(`SELECT setval(pg_get_serial_sequence('${t}', 'id'), GREATEST(COALESCE((SELECT MAX(id) FROM ${t}), 0), 1), (SELECT COUNT(*) > 0 FROM ${t}))`);
  }
}
